### ISSUE TITLE
[Sherry & Amy] 题目太长, 不能edit

### ISSUE THREAD

**Issue by lentty** [t20731/SFMoocWechatClient#19]
Unexpected end of JSON input;at pages/uploadQuestion/editQuestion page lifeCycleMethod onLoad function
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at e.onLoad (http://127.0.0.1:57444/appservice/pages/uploadQuestion/editQuestion.js:48:30)
    at e.<anonymous> (http://127.0.0.1:57444/appservice/__dev__/WAService.js:18:16345)
    at D (http://127.0.0.1:57444/appservice/__dev__/WAService.js:18:1254)
    at F (http://127.0.0.1:57444/appservice/__dev__/WAService.js:18:2027)
    at K (http://127.0.0.1:57444/appservice/__dev__/WAService.js:18:3339)
    at Function.<anonymous> (http://127.0.0.1:57444/appservice/__dev__/WAService.js:18:6274)
    at http://127.0.0.1:57444/appservice/__dev__/WAService.js:18:12486
    at http://127.0.0.1:57444/appservice/__dev__/WAService.js:5:22695
    at Array.forEach (<anonymous>)

**Comment by t20731** [comment]
进去Quiz是添加题目 如果题目和答案都特别长时， 再次编辑题目，内容丢失。
此前是将题目内容转化成string放到url里的，改为编辑题目是前端只传递id到后台获取题目信息。
